# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('bandwidth-manager', ['internet', 'traffic-control'])
    module.source = [
        'model/bandwidth-function.cc',
        'model/bwm-coordinator.cc',
        'model/bwm-local-agent.cc',
        'model/bwm-queue-disc.cc',
        'utils/tenant-id-tag.cc'
        ]

    module_test = bld.create_ns3_module_test_library('bandwidth-manager')
    module_test.source = [
        
        ]

    headers = bld(features='ns3header')
    headers.module = 'bandwidth-manager'
    headers.source = [
        'model/bandwidth-function.h',
        'model/bwm-coordinator.h',
        'model/bwm-local-agent.h',
        'model/bwm-queue-disc.h',
        'utils/tenant-id-tag.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    bld.ns3_python_bindings()

